### ISSUE TITLE
User's community

### ISSUE THREAD

**Issue by iherman** [w3c/standards-track#1]
I miss a more explicit reference to the interests of specific user communities (as opposed to implementers' interest only). An obvious [example](https://github.com/w3c/standards-track/blob/master/bp.md#socialized-proposal):  

> An initial draft of the technical specification has been written down and socialized in a community where web site / app developer, framework/took developer, and core technology implementers are represented.

I think we should emphasize that all incubations by groups at least should (if not must) prove that the proposals are driven by the concerns of real end-users. 

Another example of a [similar pattern](https://github.com/w3c/standards-track/blob/master/bp.md#success-criteria):

> The proposal enumerates the types of products (browsers, servers, frameworks, applications...) would need to support the spec for it to be successful

We should not only talk about products. User communities' adoption (e.g., language/I18N requirements, accessibility, but we may also talk about the needs of online marketing, publishing, etc. whatever is appropriate) should be clearly identified and represented. Or, at the minimum, it should be made clear by the proposals that this check is planned to be part of the planned Working Group's jobs.

I believe this is, actually, an editorial issue, but important nevertheless.

**Comment by michaelchampion** [comment]
I agree this is an editorial issue and will make changes to indicate that socialization with users as well as implementers is needed, as is analysis of what actual usage is needed for a Recommendation to be considered successful.

**Comment by michaelchampion** [comment]
I believe I've resolved this in https://github.com/w3c/standards-track/commit/7d21e4b37c04a847664e0906300eea3e706de731.  Please-reopen the issue if you disagree
