### ISSUE TITLE
target audience section doesn't include AC in decisions it shares with Director

### ISSUE THREAD

**Issue by wcarr** [w3c/standards-track#14]
> The target audience for this document includes:
>  * the Team and Director when evaluating proposals to create new Working Groups or rechartering existing Working Groups to put new work in scope;
>  * working group Chairs determining whether to publish First Public Working Drafts of specs that are in a group's chartered scope, 
>  * Advisory Committee representatives reviewing charters and Proposed Recommendations.

What the team and director consider should be the same as what the AC considers -- they both consider charters and PR - but the two bullets differ only by PR included in the Director bullet.  It also should be clearer what about the charter should be considered.  

Created PR for proposed wording change #13

Also -
What should the Director consider at Proposed REC time?  Seems the Director/AC look at the current draft and what kind of review and input it had, and at that point it doesn't matter if that was during incubation or after that as long as it was done by Proposed REC.  There are already criteria for Proposed REC in the process.  So I think that part should be clarified or removed.

**Comment by michaelchampion** [comment]
I accepted the pull request on this topic
