### ISSUE TITLE
arguments against incubation - clarify one on team participation

### ISSUE THREAD

**Issue by wcarr** [w3c/standards-track#19]
> It may be valuable for W3C team to help develop one or more proposals in the incubation stage

Does this mean: "If incubation is done outside W3C CGs or WGs, it may be more difficult for ther W3C team to help develop one or more proposals in the incubation stage"

I wasn't at the meeting where these objections were discussed, but W3C staff do participate in and sometimes lead CGs.  Was this that they are less involved, rather than not able to be involved?

That bullet should be clearer on what was suggested as preventing team participation.

**Comment by wseltzer** [comment]
Sorry, just noticing this issue. It's not that team are prohibited from working with CGs, but that sometimes team might find it valuable to incubate work in a different venue (e.g. a WG with patent commitments, or an IG with participation rules), and we shouldn't prohibit that either.

**Comment by wcarr** [comment]
I'll close this.  I thought the bullet assumed readers knew doing incubation in a CG often would mean less Team involvement than doing it in a WG, and that maybe that should be more explicit for readers who don't know that.
