### ISSUE TITLE
We are not talking only about traditional Web Sites and browsers

### ISSUE THREAD

**Issue by iherman** [w3c/standards-track#2]
W3C's concerns are not restricted to traditional web sites and browsers; we address a number of other areas with our technologies (server side issues, data on the Web, digital publishing, hybrid mobile applications, etc). Overall, the proposal *is* open in this sense (i.e., this is an editorial comment), but the examples should make it clearer to avoid misunderstandings. For example, the impression given by the example list in the [Problem statement](https://github.com/w3c/standards-track/blob/master/bp.md#problem-statement):

> What are websites forced to do without this feature being available in a standardized way? What fraction of web sites / applications are implementing a similar feature in a non-standardized way? How would users benefit from this feature if standardized?

could be extended to include some of the non-browser and/or non-client examples.

**Comment by michaelchampion** [comment]
I believe I've resolved this as you suggested in https://github.com/w3c/standards-track/commit/7d21e4b37c04a847664e0906300eea3e706de731 .  Please re-open the issue if you disagree.
