### ISSUE TITLE
Rubber stamp should not be an 'additional consideration'

### ISSUE THREAD

**Issue by iherman** [w3c/standards-track#4]
The [section on rubber stamping](https://github.com/w3c/standards-track/blob/master/bp.md#the-proposers-are-not-seeking-a-rubber-stamp-from-w3c) is, in my view, an essential readiness criterium. 

Although the proposal does refer (in the introduction) to the danger of:

> • If a CG incubates a spec that gets implemented in the browsers, it's hard to motivate them to take it to a WG for broad review
> 
> • If the CG did not work by consensus, the de facto standard might be imposed by a single strong editor or cabal of the top browsers

I am not sure how this problem is addressed among the essential criteria. At the minimum, the incubator group should explicitly consider the issues listed in the section on rubber stamping. Hence moving it to the essential criteria section, and mark it as "strongly recommended".

This is also related to Issue #3.

**Comment by michaelchampion** [comment]
I believe I've resolved this as you suggested in https://github.com/w3c/standards-track/commit/7d21e4b37c04a847664e0906300eea3e706de731 .  Please re-open the issue if you disagree.
