### ISSUE TITLE
Should there be a proof of initial consensus?

### ISSUE THREAD

**Issue by iherman** [w3c/standards-track#5]
The W3C process requires proofs, before letting a document through the process to become a standard, showing that a reasonable consensus has been found in the WG during the development process, including reviews by other communities. However, no such formal process exists for Community Groups, for example (by design). This means that an incubation group may arrive to a proposal dominated by one or two major players, and which does not, in fact, represent community consensus (or may even reflect major disagreements that are overruled by some strong players). There is no real way of knowing this.

The section on ["Socialized Proposals"](https://github.com/w3c/standards-track/blob/master/bp.md#socialized-proposal) does refer to something similar but not strongly enough for my taste. Maybe it should also state that proof should be provided for a reasonable consensus or references to major disagreements should be made known. Alternatively, a separate section should be added spelling out this criterium. 

Note that it *may* be possible for a Working Group to be formed without the incubation leading to a complete consensus, if the WG's stated job is to find such a consensus. But knowing the relevant history on this is important.

**Comment by michaelchampion** [comment]
Not sure I agree.  The point of the Recommendation Track is to generate  broad consensus, and proof of that consensus is needed to advance on the Rec track.  It seems overly restrictive to insist on that proof in order to get on the Rec track. Am I missing your point? Can you suggest a particular change -- perhaps to document any known objections to the proposal that emerged during the socialization process?

**Comment by iherman** [comment]
(We are acting as lawyers here, insofar as being paranoiac to avoid the worst cases...)

An example situation I think we should try to avoid is that we have a CG with a major internal discussion on issues and, at the end, a particularly strong party bullying everyone into a particular solution. That solution may then be put forward for a WG. That means that the WG would 'inherit' a major dissent/objection which it would have to solve. If the chartering process *knows* about this problem then W3C may decide to deal with it (or not), but this information is not necessarily around with the current CG setup.

You are right that saying:

> showing that a reasonable consensus has been found
 
may be too much to ask. But having an information on the status of the agreement and/or disagreements within the CG regarding the approach being put forward for standardization is, I believe, important for the further steps (and for W3C to decide whether it wants to go ahead). So let me modify my original comment by saying that we need a reliable, documented information on the status of consensus (or not) around the proposed technology.

**Comment by michaelchampion** [comment]
Got it, thanks.

**Comment by michaelchampion** [comment]
I believe I've resolved this as you suggested in https://github.com/w3c/standards-track/commit/7d21e4b37c04a847664e0906300eea3e706de731 .  Please re-open the issue if you disagree.
