### ISSUE TITLE
Clarify the stage at which screens apply

### ISSUE THREAD

**Issue by wseltzer** [w3c/standards-track#6]
Lots of good advice in here for assessing standards-readiness. Though I agree we shouldn't label an early-stage tech without evidence of useful support "Recommendation track," I wouldn't want us to interpret the guidance to prevent W3C team involvement in early-stage discussions of technologies, or even in the development of some of those alternatives.

I would differentiate between listing something as a named Rec-track deliverable, and letting work be incubated in a chartered group -- possibly an IG or WG, not just CG. While we don't want to make heavy investment (of Consortium or Member resources) in early-stage work, we might want to make small investments in a portfolio of early work, expecting some of it to fizzle and some to succeed.

**Comment by michaelchampion** [comment]
I agree it should be possible for the team to be involved in early-stage discussion / incubation. Can you suggest a change to this document to encourage that?   I did just now check in a version that has a section at the end  intended to resolve another issue that does talk about CGs getting Team input in advance of proposing their spec for the Rec Track.  Maybe that could be expanded to address your point?

**Comment by wseltzer** [comment]
Here's one piece: 
https://github.com/w3c/standards-track/pull/10

**Comment by michaelchampion** [comment]
I believe I've addressed both the "team involvement" and "stage at which the screen applies" issues in the 2/1/2016 draft.
