### ISSUE TITLE
what is restricted by the criteria: Charter?  what WG can do before FPWD?  publishing FPWD?

### ISSUE THREAD

**Issue by wcarr** [w3c/standards-track#8]
The requirement for an incubator spec could make it harder to get new work into a WG Charter (depending on what is actually meant be the proposal).  Charters often last 2-3 years.  

When an incubator spec is ready to move to a WG, does it wait (possibly a couple of years) to get into a WG Charter or are is the expectation that WGs would re-charter?  (Rechartering requires everyone rejoining the WG to work under the new Charter.).  

Or is their no restriction on specs being allowed in a Charter and the restriction is on when the WG is permitted to work on the spec?  E.g. any work on X must be done outside the WG until the criteria are met?

Or is the restriction on when a WG is permitted to publish a FPWD (WG is allowed to do its own incubation in preparing for a FPWD, but can't publish a premature FPWD before criteria are met)?

It should be clear which of these is intended, or if it is the WG has a choice of which of these in their Charter.

**Comment by michaelchampion** [comment]
I'm trying to keep this particular document focused on "what" questions -- what does a spec that is ready for the Rec Track look like?  It's clear from the discussion that there are a number of "how" questions that also need to be discussed, e.g. "How do we get a document ready for the Rec track [In a CG | without creating unstoppable momentum before the consensus process kicks in | without creating a lot of busy work updating charters | ...].  I have put placeholders for these in a new Process Considerations section, but it would probably be best to create a parallel best practices document for HOW to get specs ready for standardization that provides answers.
